apiVersion: apps/v1
kind: Deployment
metadata:
  name: omw-arbiter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omw-arbiter
  template:
    metadata:
      labels:
        app: omw-arbiter
    spec:
      containers:
        - name: geocode
          image: rjmregistry.azurecr.io/arbiter:latest
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 120
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: omw-arbiter
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: omw-arbiter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omw-geocode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omw-geocode
  template:
    metadata:
      labels:
        app: omw-geocode
    spec:
      containers:
        - name: geocode
          env:
            - name: SECRET_OPENWEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: omw-openweather-apikey
                  key: openweatherapikey
                  optional: false
          image: rjmregistry.azurecr.io/geocode:latest
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 120
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: omw-geocode
spec:
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: omw-geocode
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omw-forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omw-forecast
  template:
    metadata:
      labels:
        app: omw-forecast
    spec:
      containers:
        - name: forecast
          env:
            - name: SECRET_OPENWEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: omw-openweather-apikey
                  key: openweatherapikey
                  optional: false
          image: rjmregistry.azurecr.io/forecast:latest
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 120
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: omw-forecast
spec:
  ports:
    - port: 80
      targetPort: 8082
  selector:
    app: omw-forecast
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omw-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omw-ui
  template:
    metadata:
      labels:
        app: omw-ui
    spec:
      containers:
        - name: geocode
          image: rjmregistry.azurecr.io/ui:latest
          env:
            - name: vaadin.productionMode
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: omw-ui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8085
  selector:
    app: omw-ui