apiVersion: apps/v1
kind: Deployment
metadata:
  name: omw-arbiter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omw-arbiter
  template:
    metadata:
      labels:
        app: omw-arbiter
    spec:
      containers:
        - name: geocode
          image: rjmregistry.azurecr.io/arbiter:latest
---
apiVersion: v1
kind: Service
metadata:
  name: omw-arbiter
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: omw-arbiter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omw-geocode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omw-geocode
  template:
    metadata:
      labels:
        app: omw-geocode
    spec:
      containers:
        - name: geocode
          env:
            - name: SECRET_OPENWEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: omw-openweather-apikey
                  key: openweatherapikey
                  optional: false
          image: rjmregistry.azurecr.io/geocode:latest
---
apiVersion: v1
kind: Service
metadata:
  name: omw-geocode
spec:
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: omw-geocode
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omw-forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omw-forecast
  template:
    metadata:
      labels:
        app: omw-forecast
    spec:
      containers:
        - name: forecast
          env:
            - name: SECRET_OPENWEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: omw-openweather-apikey
                  key: openweatherapikey
                  optional: false
          image: rjmregistry.azurecr.io/forecast:latest
---
apiVersion: v1
kind: Service
metadata:
  name: omw-forecast
spec:
  ports:
    - port: 80
      targetPort: 8082
  selector:
    app: omw-forecast