spring:
  cloud:
    vault:
      token: 00000000-0000-0000-0000-000000000000
      host: localhost
      port: 8200
      scheme: http
  application:
    name: current-weather
  config:
    import: vault://
server:
  port: 8082