name: Single Project - CI Build

on:
  workflow_dispatch:
    inputs:
      environment:
        type: project_choice
        description: Choose which project to build
        options:
        - arbiter
        - forecast
        - geocode

jobs:
  build:
    name: Build Main Branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Project
        working-directory: ./${{ github.event.inputs.project_choice }}
        run: mvn --batch-mode package